/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anocter_Beep */

#ifndef _Included_com_anocter_Beep
#define _Included_com_anocter_Beep
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anocter_Beep
 * Method:    beep
 * Signature: (DJ)V
 */
JNIEXPORT void JNICALL Java_com_anocter_Beep_beep
  (JNIEnv *, jclass, jdouble, jlong);

#ifdef __cplusplus
}
#endif
#endif
